apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chat-app
  labels:
    app: chat-app
    tier: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
